### ISSUE TITLE
Code coevrage for individual files doesn’t show up in the comment if tests files are modified but corresponding source file isn't changed

### ISSUE THREAD

**Issue by shubhnik** [ArtiomTr/jest-coverage-report-action#207] opened 2021-12-20 08:16 UTC
### Describe a bug

If I write unit tests and increase code coverage for a file that already exists, it doesn't show the improved coverage for that specific file in the comment.

### Expected behavior
When test files are improved without touching anything in source files, the code coverage increment should show up in the comments.

### Details

-   Action version: `artiomtr/jest-coverage-report-action@v2.0-rc.6`
-   OS, where your action is running (windows, linux): `linux`
-   <details><summary>action.yml file</summary>

        ```yml
        jobs:
          coverage:
              runs-on: self-hosted
              if: "!contains(github.event.head_commit.message, '[skip ci]')"
              steps:
                - name: Checkout Codebase
                  uses: actions/checkout@v2
                  with:
                    token: ${{ secrets.CI_BOT_TOKEN }}
                - name: Setup Node v14
                  uses: actions/setup-node@v2
                  with:
                    node-version: "14"
                - name: Install Yarn
                  run: npm install -g yarn
                - name: Code coverage
                  uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
                  with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    test-script: yarn test:coverage
                    package-manager: yarn
                    annotations: none
        ```

    </details>

-   <details><summary>Screenshots</summary>

    1. Changes in 2 test files which improves code coverage:
           <img width="1346" alt="Screenshot 2021-12-20 at 1 33 11 PM" src="https://user-images.githubusercontent.com/9150371/146733110-0461b5e5-041b-4b4b-aaae-3dd79c5c92ab.png">
           
    2. But those improved changes for the respective files is not shown individually in the comment:
           <img width="781" alt="Screenshot 2021-12-20 at 1 33 29 PM" src="https://user-images.githubusercontent.com/9150371/146733228-6328abb6-4dd7-4bfe-8b50-3e4a60d949cc.png">
</details>

**Comment by ArtiomTr** [comment] 2021-12-20 19:24
Hello @shubhnik 👋,

Could you please try solution described in this https://github.com/ArtiomTr/jest-coverage-report-action/issues/171#issuecomment-936448008, and confirm if it worked for you?

**Comment by shubhnik** [comment] 2021-12-21 04:32
Hi, @ArtiomTr I have this in my `jest.config.js`. I think the issue you pointed to is different too. That issue is related to newly added files not shown in the comment which is working fine for me. The issue with my setup is that already existing files whose unit tests are written now without changing the source code are not being shown in the comment.

<img width="415" alt="Screenshot 2021-12-21 at 9 59 39 AM" src="https://user-images.githubusercontent.com/9150371/146871262-c1eac17a-3311-46fa-9c77-e79e86adff69.png">

**Comment by ArtiomTr** [comment] 2021-12-23 23:55
@shubhnik, oh, sorry, I misunderstood your question 😄 

Currently, this action has only 2 types of details - **new** file coverage and **old** files with decreased coverage. There is a reason why these two events should attract more attention for the user.
- The **new** file coverage is required to check if new feature / module is properly covered with tests. 
- **Old** files with decreased coverage are visible because when somebody modifies function's / module's behavior, it's very easy to break some things, or add new behavior which was not described.

But I do not see a reason for displaying coverage for files, which were covered more. The fact of covering files with tests does not require additional attention - that's good, but it's already visible by summary rows.

I've described my opinion on this question, and currently, I don't really see the necessity of adding this feature, so I'm closing this issue for now. However, I'm always open to conversation, so if you have any arguments why this feature should be added to this action - feel free to express your opinion!

**Closed** 2021-12-23 23:56 UTC
Labels: enhancement

**Comment by shubhnik** [comment] 2022-01-03 18:40
Hi @ArtiomTr this is a common effort where an organization starts adopting testing. In this case for example our team, we set a threshold of let say 80% coverage for any existing file we write tests for. Adding a section for **new files covered(increased coverage🔼)** ensures we are on right track and abiding by the thresholds.

I hope adding this section won't be a big effort? Though happy to contribute if this ask makes sense.

**Comment by ArtiomTr** [comment] 2022-02-01 16:36
@shubhnik,

Sorry for late reply. The problem is that this action grows drastically. Each new feature must not only be implemented - it must go through several "steps". First of all, it should be implemented. Then, it requires tests. After that, I should analyze, if it doesn't conflict with other functionality. And even after all these steps are completed, I should maintain it, check the bugs, answer the questions about it. This action has a lot of features, and it takes a lot of effort to maintain it. So I'm sorry, but I'll not add this feature.

However, this action is completely open-sourced, it has MIT license, so this means, nothing stops you from forking it, modifying, and then publishing to the marketplace. So if you really want to see this feature, feel free to fork & publish your own version of this action. 

Hope I clarified all the details about this issue. If you have questions or just want to discuss something regarding this question - feel free to ping me.
