### ISSUE TITLE
Problems running only collect coverage

### ISSUE THREAD

**Issue by gabiwassan** [ArtiomTr/jest-coverage-report-action#113] opened 2021-07-12 10:21 UTC
Hi,
I'm trying to use our action just to collect my report and comment on github that information, but I can't run successfully.

My action:
```
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          working-directory: ${{ env.PATH_WAZUH-APP }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

Error result:
```
Run artiomtr/jest-coverage-report-action@v2.0-rc.1
  with:
    github-token: ***
    skip-step: all
    test-script: npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
    icons: emoji
    annotations: all
    package-manager: npm
  env:
    “PATH_WAZUH-APP: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/”
Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'report.json'
}
/usr/bin/git fetch --all --depth=1
fatal: not a git repository (or any of the parent directories): .git
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 128
    at f._setResult (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:11470)
    at f.CheckComplete (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:10900)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:9944)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
/usr/bin/git checkout -f 4.3-7.10
fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128


```

Here [my action.yml](https://github.com/wazuh/wazuh-kibana-app/blob/f5e2a9069cdba7288c86e70140fc36bb1cd6ab59/.github/workflows/wazuh-unit-test.yml)

**Comment by ArtiomTr** [comment] 2021-07-22 20:06
Hello @gabiwassan! 👋

Sorry for the late reply. As far as I can see, in your configuration the `working-directory` has correct value, but it is not being passed to the action. I'm not sure, but it seems to me that the issue is with the name of the variable: try to rename it so that no hyphen is used (for example `PATH_WAZUH_APP`). If that doesn't work, try running an action with a configuration like this:

```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
#       here is the change    ↓
          working-directory: kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

Hope my answer will help you!

**Comment by ig-onoffice-de** [comment] 2021-07-28 12:58
I have the same problem. working-directory is given as literal
`working-directory: frontend`
But getting error
`Could not read report file located at frontend/report.json [Error: ENOENT: no such file or directory, open 'frontend/report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'frontend/report.json'
}`
Also tried  `working-directory: ./frontend` and `working-directory: frontend/` which should be the same.

**Comment by ArtiomTr** [comment] 2021-07-28 16:17
Hello @ig-onoffice-de,

Could you send me the full `action.yml` file as well as a screenshot of the console output of the action? Thanks in advance.

**Comment by gabiwassan** [comment] 2021-08-03 12:35
> Hello @gabiwassan! 
> 
> Sorry for the late reply. As far as I can see, in your configuration the `working-directory` has correct value, but it is not being passed to the action. I'm not sure, but it seems to me that the issue is with the name of the variable: try to rename it so that no hyphen is used (for example `PATH_WAZUH_APP`). If that doesn't work, try running an action with a configuration like this:
> 
> ```yaml
>       - name: Step 08 - Run Tests & Collect Coverage
>         run: |
>           echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
>           cd ./kibana/plugins/wazuh-kibana-app
>           ls -la
>           echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
>           yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
> 
>       - name: Step 09 - Comment coverage
>         uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
>         with:
> #       here is the change    ↓
>           working-directory: kibana/plugins/wazuh-kibana-app/
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           skip-step: all
> ```
> 
> Hope my answer will help you!

Hi @ArtiomTr, don't apologize, it's okay 😃 
I tried with this configuration, but if it keeps generating the same error: 
```
fatal: not a git repository (or any of the parent directories): .git
Error fetching git repository Error: The process '/usr/bin/git' failed with exit code 128
    at f._setResult (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:11470)
    at f.CheckComplete (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:10900)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artiomtr/jest-coverage-report-action/v2.0-rc.1/dist/index.js:2:9944)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
/usr/bin/git checkout -f 4.3-7.10
fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by ArtiomTr** [comment] 2021-08-04 06:29
@gabiwassan, could you please send the action arguments as you did in your first comment? Like this:

> Error result:
> 
> ```
> Run artiomtr/jest-coverage-report-action@v2.0-rc.1
>   with:
>     github-token: ***
>     skip-step: all
>     test-script: npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
>     icons: emoji
>     annotations: all
>     package-manager: npm
>   env:
>     “PATH_WAZUH-APP: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/”
> Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {

Also, could you try please to set up working-directory variable as shown below:

```yml
          working-directory: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/
```

**Comment by gabiwassan** [comment] 2021-08-04 13:18
@ArtiomTr [here](https://github.com/wazuh/wazuh-kibana-app/blob/9d70824b0ec473e1909a5bfd080c3a973214d3f5/.github/workflows/wazuh-unit-test.yml) the action.yml 
Y try with this: `working-directory: /home/runner/work/wazuh-kibana-app/wazuh-kibana-app/kibana/plugins/wazuh-kibana-app/
` but i had the same error.

**Comment by ArtiomTr** [comment] 2021-08-05 10:18
@gabiwassan,

I think that the problem is that you're changing directory in previous step, to collect coverage. You can try to simply remove `working-directory` option from your `action.yml` file, or just to exit working directory in previous step. So possible configurations could be:
1. Remove working directory:
```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
#         working-directory: ./kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```
2. Exit in previous step:
```yml
      - name: Step 08 - Run Tests & Collect Coverage
        run: |
          echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
          cd ./kibana/plugins/wazuh-kibana-app
          ls -la
          echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
          yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
#             ↓
          cd ../../..

      - name: Step 09 - Comment coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
# and specify working directory ↓
          working-directory: ./kibana/plugins/wazuh-kibana-app/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
```

If these solutions do not help you, then wait until #118 is merged into the master.

**Comment by gabiwassan** [comment] 2021-08-05 13:45
> @gabiwassan,
> 
> I think that the problem is that you're changing directory in previous step, to collect coverage. You can try to simply remove `working-directory` option from your `action.yml` file, or just to exit working directory in previous step. So possible configurations could be:
> 
> 1. Remove working directory:
> 
> ```yaml
>       - name: Step 08 - Run Tests & Collect Coverage
>         run: |
>           echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
>           cd ./kibana/plugins/wazuh-kibana-app
>           ls -la
>           echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
>           yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
> 
>       - name: Step 09 - Comment coverage
>         uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
>         with:
> #         working-directory: ./kibana/plugins/wazuh-kibana-app/
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           skip-step: all
> ```
> 
> 1. Exit in previous step:
> 
> ```yaml
>       - name: Step 08 - Run Tests & Collect Coverage
>         run: |
>           echo “PATH_WAZUH-APP=$GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/” >> $GITHUB_ENV
>           cd ./kibana/plugins/wazuh-kibana-app
>           ls -la
>           echo $GITHUB_WORKSPACE/kibana/plugins/wazuh-kibana-app/
>           yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
> #             ↓
>           cd ../../..
> 
>       - name: Step 09 - Comment coverage
>         uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
>         with:
> # and specify working directory ↓
>           working-directory: ./kibana/plugins/wazuh-kibana-app/
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           skip-step: all
> ```
> 
> Also, if these configurations not solved your issue, try to remove step 8 and let this action collect coverage for you:
> 
> ```yaml
>       - name: Step 08 - Collect & comment coverage
>         uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
>         with:
>           working-directory: ./kibana/plugins/wazuh-kibana-app/
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           test-script: yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
>           package-manager: yarn
> ```
> 
> If these solutions do not help you, then wait until #118 is merged into the master.

I have tried the 3 options, the first two I get the same error, with the third option shows me the following error:

> Run artiomtr/jest-coverage-report-action@v2.0-rc.3
> with:
>     working-directory: ./kibana/plugins/wazuh-kibana-app/
>     github-token: ***
>     test-script: yarn run test:jest --silent --ci --testLocationInResults --colors --coverage --json --outputFile=report.json
>     package-manager: yarn
>     icons: emoji
>     annotations: all
>     skip-step: none
>   env:
>     NODE_10-23-1: 10.23.1
>     NODE_12-22-3: 12.22.3
>     YARN_1-21-1: 1.21.1
>     KIBANA_TAG: v7.10.2
> Running using node v10.23.1
> Error: Callback must be a function
> Error: Process completed with exit code 1.


I wait for that merge 👍🏼  thanks!

**Comment by ArtiomTr** [comment] 2021-11-03 12:44
@laurislokalise, this repository is open to all types of contributions, so if you think displaying the absolute path in the error will help you understand the problem more clearly, feel free to open the PR.

However, the problem may go deeper than it might seem at first glance. The problem might be that the action is not generating a report file, which is a much deeper problem. In version `v2.0-rc.6`, the action prints the entire progress, which stages were `completed` / `skipped` / `failed` and why.

So could you please send me the full screenshot of the console? This would help me a lot.

**Comment by laurislokalise** [comment] 2021-11-04 11:31
@ArtiomTr here is the screenshot of the console:
![DeepinScreenshot_select-area_20211104132842](https://user-images.githubusercontent.com/74536758/140306143-905f3d97-8e47-44c3-ab07-231e0a28648b.png)

**Comment by ArtiomTr** [comment] 2021-11-05 14:17
@laurislokalise, thank you! Now, I see that there is two big issues with your case:
1. Action continues report even after reading report failed.
2. Action not finds the report file.

The first problem requires a deeper understanding, more time, so I've created a separate issue for it. (#190)

The second issue is caused because of not intuitive behavior of this action. This is the fragment of code which causes problem: https://github.com/ArtiomTr/jest-coverage-report-action/blob/8a4ee4425baec6bdc5ccc1f507c5c1726cc4c9e4/src/stages/collectCoverage.ts#L21-L33
You're expecting, that by specifying `workingDirectory` and `coverage-file`, the action will concatenate those properties, and will try to read file at path `workingDirectory/coverage-file`. However, it just ignores `workingDirectory` when `coverage-file` is specified.

So the solution would be to simply concatenate those two properties here:
https://github.com/ArtiomTr/jest-coverage-report-action/blob/8a4ee4425baec6bdc5ccc1f507c5c1726cc4c9e4/src/stages/collectCoverage.ts#L26

That's all. So now that the problem has been found, you can start working on it if you would like to.

**Closed** 2021-11-11 13:24 UTC
Labels: question

**Comment by lixiaofa** [comment] 2023-09-27 03:25
I also have the same problem
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/23230215/e4fdd76f-2712-4a94-ab33-abea50b8b50e)
@ArtiomTr
